# Generated by Django 4.0.2 on 2022-09-15 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате 7XXXXXXXXXX, Х - цифра от 0 до 9', regex='^7\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
